# Generated by Django 5.2.4 on 2026-09-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0012_alter_tripmember_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='trip_covers/'),
        ),
    ]
